---
title: "aa-hex_maps_with_water_points"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{aa-hex_maps_with_water_points}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo=FALSE,
  collapse = TRUE,
  comment = "#>",
  warning = F, 
  message = F
)
```

```{r, echo=FALSE}
library(here)
library(tidyverse)
devtools::load_all()
theme_set(theme_bw())
library(sf)
library(tmap)
library(leaflet)
```

## Hex Maps with strategic water points

```{r,echo=FALSE}

#' load_h2r_data
#'
#' @return
#' @export
#' @description function to load H2R data set - will use environment key to specify base data directory
#' @examples
load_h2r_data <-  function(main_folder_path, data_path){
  
  main_folder_path <-  Sys.getenv("SOM_2203_WASH_DATA")
  data_path <- "data/202209/h2r_aggregated/SOM1901_H2R_hex_400km_May_2022.csv"
  
  h2r_data <- readr::read_csv(file.path(main_folder_path, data_path))# |> 
    # mutate(latitude = parse_number(X),
    #        longitude = parse_number(geometry))
  
  return(h2r_data)
}

#' select_h2r_indicators
#'
#' @return
#' @export
#' @description function to select relevant h2r indicators from data set
#' @examples
select_h2r_indicators <- function(input_df, country_code="som"){
  if(country_code =="som"){
    
    h2r_cols <- c("hex_4000km",
                  "climatic_shock",
                  "crop_loss_reasons",
                  "primary_reason_moved",
                  "idp_new_arrivals",
                  "idp_arrived_reason",
                  "idp_pull_factors",
                  "hc_push_main",
                  "mainsource_water",
                  "responsible_water_fetching",
                  "surfacewater_drinking",
                  "gettingwater_time",
                  "water_sufficient_lastmonth",
                  "stagnant_water_near",
                  "people_using_latrines",
                  "barriers_usetoilets",
                  "waste_disposal",
                  "handwashing_access"
      )

  }

  df_h2r_cols <- input_df |>
    # select(any_of(purrr::map_chr(h2r_cols, ~.x))) |>
    select(contains(h2r_cols)) |>
    mutate(country_code = country_code)
  return(df_h2r_cols)
}


#' load_h2r_indictors
#'
#' @return
#' @export
#' @description combination of `load_h2r_data` and `select_h2r_indicators` to quicky load only data with only relelvant indicators
#' @examples
load_h2r_indicators <-  function(ctry_code = "som"){
  df <-load_h2r_data(main_folder_path = Sys.getenv("SOM_2203_WASH_DATA"), 
                     data_path = "data/202209/h2r_aggregated/SOM1901_H2R_hex_400km_May_2022.csv")
  
  df_processed <-  df |> 
    select_h2r_indicators(country_code = ctry_code)
  return(df_processed)  
}

```


```{r, echo=FALSE}

df_som_data <- load_h2r_indicators(ctry_code = "som")

df_som_data_shape <- som_hex |> 
  left_join(df_som_data, by = c("GRID_ID" = "hex_4000km"))


df_water_points_shape <- load_swp() |> 
  st_as_sf(coords = c("longitude","latitude"), crs = 4326)


# I want to clip the point file to just H2R areas mainly so that we can use the {leaflet} label functionality which doesn't work in {leafgl}
h2r_bbox <- som_hex |> 
  filter(GRID_ID %in% df_som_data$hex_4000km) |> 
  st_bbox() |> 
  st_as_sfc()

swp_in_h2r_bbox<-df_water_points_shape[h2r_bbox,]
swp_in_h2r_bbox_functional <- swp_in_h2r_bbox |> 
  mutate(
    functioning= tolower(functioning)
  ) |> 
  filter(functioning=="yes")
```

### H2R with strategic water data

```{r, echo=FALSE, fig.height=10, fig.width=10}

pal <- colorBin(palette = "YlOrBr", domain = df_som_data_shape$mainsource_water_borehole, bins = 5, na.color = "#b6b6b7")

points_pal <- colourvalues::color_values_rgb(df_water_points_shape$water_source_type, include_alpha = FALSE)/255
dark_pal <-RColorBrewer::brewer.pal(n=6, name = "Dark2")

points_facpal <- colorFactor(palette = dark_pal, domain = df_water_points_shape$water_source_type)

df_som_data_polygons <- sf::st_cast(x = df_som_data_shape,to = 'POLYGON')

###########################################################################3
# Reported borehole as main source
##############################################################################
leaflet() %>% 
  addProviderTiles(providers$Esri.WorldGrayCanvas, options = providerTileOptions(minZoom = 3.75, maxZoom = 10.5), 
                   group="Esri Gray Canvas") |> 
  addProviderTiles(providers$HERE.satelliteDay,  options = providerTileOptions(minZoom = 3.75, maxZoom = 10.5), 
                   group="Here SatelliteDay") |> 
  addProviderTiles(providers$Esri.WorldImagery,  options = providerTileOptions(minZoom = 3.75, maxZoom = 10.5), 
                   group="Esri World Imagery") |> 
  leafgl::addGlPolygons(data = df_som_data_polygons, fillColor = ~pal(mainsource_water_borehole), group = "main_water_sources") |> 
  
  #annoyingly {leafgl} label doesn't work so let's use leaflet -- this is why i clipped the point file
  addCircleMarkers(data = swp_in_h2r_bbox_functional,
                   fillColor = ~points_facpal(water_source_type),
                   color= NA,
                   fillOpacity = 1,
                   group = "water_source_type",
                   label = ~water_source_type) |>
  addLegend(position ="bottomright",pal = points_facpal,
            
            values =swp_in_h2r_bbox_functional$water_source_type, 
            # values = unique(swp_in_h2r_bbox$water_source_type),
            title = "Water Sources Types",
            opacity  = 1,
            na.label = ""
  ) |> 
  addLayersControl(
    baseGroups = c("Esri Gray Canvas", "Here SatelliteDay", "Esri World Imagery"),
    overlayGroups = c("main_water_sources", "water_source_type"),
    options = layersControlOptions(collapsed = FALSE)
  )



###########################################################################3
# Reported water_well_unprotected as main source
##############################################################################
leaflet() %>% 
  addProviderTiles(providers$Esri.WorldGrayCanvas, 
                   options = providerTileOptions(minZoom = 3.75, maxZoom = 10.5), 
                   group="Esri Gray Canvas") |> 
  addProviderTiles(providers$HERE.satelliteDay, 
                   options = providerTileOptions(minZoom = 3.75, maxZoom = 10.5), 
                   group="Here SatelliteDay") |> 
  addProviderTiles(providers$Esri.WorldImagery, 
                   options = providerTileOptions(minZoom = 3.75, maxZoom = 10.5), 
                   group="Esri World Imagery") |> 
  leafgl::addGlPolygons(data = df_som_data_polygons, fillColor = ~pal(mainsource_water_well_unprotected), group = "main_water_sources") |> 
  
  #annoyingly {leafgl} label doesn't work so let's use leaflet -- this is why i clipped the point file
  addCircleMarkers(data = swp_in_h2r_bbox,
                   fillColor = ~points_facpal(water_source_type),
                   color= NA,
                   fillOpacity = 1,
                   group = "water_source_type",
                   label = ~water_source_type) |>
  addLegend(position ="bottomright",pal = points_facpal,
            
            values =swp_in_h2r_bbox$water_source_type, 
            # values = unique(swp_in_h2r_bbox$water_source_type),
            title = "Water Sources Types",
            opacity  = 1,
            na.label = ""
  ) |> 
  addLayersControl(
    baseGroups = c("Esri Gray Canvas", "Here SatelliteDay", "Esri World Imagery"),
    overlayGroups = c("main_water_sources", "water_source_type"),
    options = layersControlOptions(collapsed = FALSE)
  )

```



