---
title: "aa-maps_for_indicators"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{aa-maps_for_indicators}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo=FALSE,
  collapse = TRUE,
  comment = "#>",
  warning = F, 
  message = F
)
```

```{r, echo=FALSE}
library(here)
library(tidyverse)
# library(somaliaWASH)
theme_set(theme_bw())
library(sf)
library(tmap)
```

## Maps for SOM WASH Indicators

```{r,echo=FALSE}

#' load_h2r_data
#'
#' @return
#' @export
#' @description function to load H2R data set - will use environment key to specify base data directory
#' @examples
load_h2r_data <-  function(main_folder_path, data_path){
  
  main_folder_path <-  Sys.getenv("SOM_2203_WASH_DATA")
  data_path <- "data/202209/raw/REACH_H2R_0522-2607_data2.csv"
  
  h2r_data <- readr::read_csv(file.path(main_folder_path, data_path)) |> 
    mutate(latitude = parse_number(X),
           longitude = parse_number(geometry))
  
  return(h2r_data)
}

#' select_h2r_indicators
#'
#' @return
#' @export
#' @description function to select relevant h2r indicators from data set
#' @examples
select_h2r_indicators <- function(input_df, country_code="som"){
  if(country_code =="som"){
    h2r_cols <- list(
      `uuid` = "uuid",
      `District` = "district_info",
      `Hex` = "hex_4000km",
      `Base` = "base",
      `info settlement` = "info_settlement",
      `Latitude` = "latitude",
      `Longitude` = "longitude",
      `Flood` = "climatic_shock.flood",
      `Failed rains` = "climatic_shock.no_rain",
      `Drought` = "climatic_shock.drought",
      `Locust invation` = "climatic_shock.locusts",
      `Wild fires` = "climatic_shock.fires",
      `Crop loss reasons` = "crop_loss_reasons",
      `Crop loss reasons locusts` = "crop_loss_reasons.locusts",
      `Crop loss reasons no rain` = "crop_loss_reasons.no_rain",
      `Crop loss reasons flooding` = "crop_loss_reasons.flooding",
      `Crop loss reasons no irrigation` = "crop_loss_reasons.no_irrigation",
      `Crop loss reasons high temperature` = "crop_loss_reasons.high_temperature",
      `Crop loss reasons other` = "crop_loss_reasons.other",
      `Reason moved` = "primary_reason_moved",
      `Reason moved to access water` = "primary_reason_moved.access_water",
      `Reason moved to access food` = "primary_reason_moved.access_food",
      `Reason moved to better security` = "primary_reason_moved.better_security",
      `Reason moved to jobsa vailable` = "primary_reason_moved.jobsa_vailable",
      `Reason moved to shelters available` = "primary_reason_moved.shelters_available",
      `Reason moved to better services` = "primary_reason_moved.better_services",
      `New IDP arrivals` = "idp_new_arrivals",
      `New IDP arrivals reason climatic shock` = "idp_arrived_reason.climatic_shock",
      `New IDP arrivals reason lack food` = "idp_arrived_reason.lack_food",
      `New IDP arrivals reason lack water` = "idp_arrived_reason.lack_water",
      `New IDP arrivals reason lack income` = "idp_arrived_reason.lack_income",
      `New IDP arrivals reason no services` = "idp_arrived_reason.no_services",
      `New IDP arrivals reason eviction` = "idp_arrived_reason.eviction",
      `New IDP arrivals reason insecurity` = "idp_arrived_reason.insecurity",
      `IDP pull factors` = "idp_pull_factors",
      `IDP pull factors water` = "idp_pull_factors.access_water",
      `IDP pull factors food` = "idp_pull_factors.access_food",
      `IDP pull factors security` = "idp_pull_factors.better_security",
      `IDP pull factors jobs` = "idp_pull_factors.presence_jobs",
      `IDP pull factors shelters` = "idp_pull_factors.availability_shelters",
      `IDP pull factors services` = "idp_pull_factors.better_services",
      `HC push main` = "hc_push_main",
      `Main source water` = "mainsource_water",
      `Responsible water fetching` = "responsible_water_fetching",
      `Surfacewater drinking` = "surfacewater_drinking",
      `Gettingwater time` = "gettingwater_time",
      `Water sufficient lastmonth` = "water_sufficient_lastmonth",
      `Stagnant water near` = "stagnant_water_near",
      `People using latrines` = "people_using_latrines",
      `Barriers usetoilets no barrier` = "barriers_usetoilets.no_barrier",
      `Barriers usetoilets not available` = "barriers_usetoilets.not_available",
      `Barriers usetoilets insufficient` = "barriers_usetoilets.insufficient",
      `Barriers usetoilets not funtional` = "barriers_usetoilets.not_funtional",
      `Barriers usetoilets overcrowded` = "barriers_usetoilets.overcrowded",
      `Barriers usetoilets too dirty` = "barriers_usetoilets.too_dirty",
      `Barriers usetoilets too far` = "barriers_usetoilets.too_far",
      `Barriers usetoilets not common` = "barriers_usetoilets.not_common",
      `Barriers usetoilets women notsafe` = "barriers_usetoilets.women_notsafe",
      `Barriers usetoilets pwd notsafe` = "barriers_usetoilets.pwd_notsafe",
      `Barriers usetoilets child notsafe` = "barriers_usetoilets.child_notsafe",
      `Barriers usetoilets night notsafe` = "barriers_usetoilets.night_notsafe",
      `Waste disposal` = "waste_disposal",
      `Hand washing access` = "handwashing_access"
    )
  }

  df_h2r_cols <- input_df |>
    select(any_of(purrr::map_chr(h2r_cols, ~.x))) |>
    mutate(country_code = country_code)
  return(df_h2r_cols)
}


#' load_h2r_indictors
#'
#' @return
#' @export
#' @description combination of `load_h2r_data` and `select_h2r_indicators` to quicky load only data with only relelvant indicators
#' @examples
load_h2r_indicators <-  function(ctry_code = "som"){
  df <-load_h2r_data()
  
  df_processed <-  df |> 
    select_h2r_indicators(country_code = ctry_code)
  return(df_processed)  
}

```


```{r, echo=FALSE}

df_som_data <- load_h2r_indicators(ctry_code = "som")

df_som_data_sf <- df_som_data |> 
  st_as_sf(coords = c("Longitude","Latitude"), crs = 4326)

df_som_data_shape <- spData::world |> 
  filter(name_long %in% c("Somalia", "Somaliland"))

```

### Looking into Shocks and reasons for crop loss

```{r, echo=FALSE, fig.width=10}
# datapasta::vector_paste_vertical()
analysis_cols_shocks <- c("Flood",
                          "Failed rains",
                          "Drought",
                          "Locust invation",
                          "Wild fires",
                          "Crop loss reasons",
                          "Crop loss reasons locusts",
                          "Crop loss reasons no rain",
                          "Crop loss reasons flooding",
                          "Crop loss reasons no irrigation",
                          "Crop loss reasons high temperature")

purrr::map(analysis_cols_shocks, ~map_with_tmap(df_som_data_shape, df_som_data_sf, .x, input_ctry_code = "som"))


```

### Looking into Displacement indicators

```{r, echo=FALSE, fig.width=10}
# datapasta::vector_paste_vertical()
analysis_cols_displacement <- c("Reason moved",
                                "Reason moved to access water",
                                "Reason moved to access food",
                                "Reason moved to better security",
                                "Reason moved to jobsa vailable",
                                "Reason moved to shelters available",
                                "Reason moved to better services",
                                "New IDP arrivals",
                                "New IDP arrivals reason climatic shock",
                                "New IDP arrivals reason lack food",
                                "New IDP arrivals reason lack water",
                                "New IDP arrivals reason lack income",
                                "New IDP arrivals reason no services",
                                "New IDP arrivals reason eviction",
                                "New IDP arrivals reason insecurity",
                                "IDP pull factors water",
                                "IDP pull factors food",
                                "IDP pull factors security",
                                "IDP pull factors jobs",
                                "IDP pull factors shelters",
                                "IDP pull factors services",
                                "HC push main")

purrr::map(analysis_cols_displacement, ~map_with_tmap(df_som_data_shape, df_som_data_sf, .x, input_ctry_code = "som"))

```

### Looking into WASH indicators

```{r,echo=FALSE, fig.width=10}
# datapasta::vector_paste_vertical()
analysis_cols_wash <- c("Main source water",
                        "Responsible water fetching",
                        "Surfacewater drinking",
                        "Gettingwater time",
                        "Water sufficient lastmonth",
                        "Stagnant water near",
                        "People using latrines",
                        "Barriers usetoilets no barrier",
                        "Barriers usetoilets not available",
                        "Barriers usetoilets insufficient",
                        "Barriers usetoilets not funtional",
                        "Barriers usetoilets overcrowded",
                        "Barriers usetoilets too dirty",
                        "Barriers usetoilets too far",
                        "Barriers usetoilets not common",
                        "Barriers usetoilets women notsafe",
                        "Barriers usetoilets pwd notsafe",
                        "Barriers usetoilets child notsafe",
                        "Barriers usetoilets night notsafe",
                        "Waste disposal",
                        "Hand washing access")

purrr::map(analysis_cols_wash, ~map_with_tmap(df_som_data_shape, df_som_data_sf, .x, input_ctry_code = "som"))

```


